# Generated by Django 2.2.6 on 2019-11-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('econtact', models.CharField(max_length=15)),
            ],
        ),
    ]
